### ISSUE TITLE
Windows Compatibility

### ISSUE THREAD

**Issue by S0UL4** [obfusk/apksigcopier#100]
Hello everyone,

I have a question that might seem simple, but I'm encountering an issue. When I run a Python script on Ubuntu, it successfully signs an unsigned app. However, when I switch to Windows, although I can generate the output APK, it remains unsigned.

Could anyone provide some assistance?

Thank you!

**Comment by obfusk** [comment]
Please don't open both and issue and a discussion for the same question. Duplicate of #101.
