### ISSUE TITLE
remove redundant do_ prefix from public API functions

### ISSUE THREAD

**Issue by eighthave** [obfusk/apksigcopier#34]
Also, I just noticed, your functions are named with a `do_` prefix.  I only know that pattern from C code, where that marks the private implementation, meaning functions that should not be exposed.  How about just using `copy(), patch(), extract()`?

**Comment by obfusk** [comment]
That's to avoid name collisions with the functions that implement the CLI. And renaming those would change the names of the CLI commands.

```py
    @cli.command(help="""
        Copy (extract & patch) signatures from signed to unsigned APK.
    """)
    @click.option("--v1-only", type=NAY, default=NO, show_default=True)
    @click.argument("signed_apk", type=click.Path(exists=True, dir_okay=False))
    @click.argument("unsigned_apk", type=click.Path(exists=True, dir_okay=False))
    @click.argument("output_apk", type=click.Path(dir_okay=False))
    def copy(*args, **kwargs):
        do_copy(*args, **kwargs)
```

**Comment by obfusk** [comment]
Unless you have anything to add, I'm considering this a `wontfix`.

**Comment by eighthave** [comment]
sure that's fine
