### ISSUE TITLE
implement Python unittest test suite using apksigner's test files

### ISSUE THREAD

**Issue by eighthave** [obfusk/apksigcopier#39]
_apksigner_ has an extensive set of test APKs as part of its test suite.  It is a good source of APKs to build tests around to make sure that all _apksigcopier_ can handle all the variations that APKs can have.

https://android.googlesource.com/platform/tools/apksig/+/refs/tags/android-mainline-11.0.0_r6/src/test/resources/com/android/apksig?autodive=0%2F%2F%2F%2F

**Comment by obfusk** [comment]
Good idea. I'll look into that when I have the time.

I think I just fixed `apksigcopier patch` for APKs w/o v1 signatures in f9ccbcb (in addition to updating the docs for the environment variables etc.).

**Comment by obfusk** [comment]
I added some tests using those APKs in ddc3ff189811997bf5e97dba2ae7a79dc47216e0.

**Comment by eighthave** [comment]
FYI you might be interested to know that there is already a pure Python library 
that implements APK signing and verification.  I forget the name, its in the 
_fdroidserver_ issue.

**Comment by obfusk** [comment]
> FYI you might be interested to know that there is already a pure Python library that implements APK signing and verification. I forget the name, its in the _fdroidserver_ issue.

I saw Python code that did v1 only; and Python code that did *everything* in Python, including the cryptography, which seems like a bad idea to me.

**Comment by eighthave** [comment]
Pure Python for APK Signature verification would be great to have.  Have the 
code in pure Python makes it a lot easier to deal with cross-platform.  APK 
Signature verification in _fdroidserver_ is about usability, not security.  It 
is there to make sure that only valid APKs are included in repos.  Android OS is 
the true enforcer of the APK Signature.  I suppose there is a security component 
to `AllowedAPKSigningKeys:` but given the _apksigner_ test suite, I think a pure 
Python implementation that passes that would be good enough, security-wise.

**Comment by obfusk** [comment]
> APK Signature verification in _fdroidserver_ is about usability, not security.

I'd argue its use to verify reproducible builds is about security though.

**Comment by obfusk** [comment]
> I think a pure Python implementation that passes that would be good enough, security-wise.

`apksigtool`'s verification is mostly complete now.

**Comment by obfusk** [comment]
> apksigtool's verification is mostly complete now.

But I'd like some independent verification that I got everything sufficiently correct.
