### ISSUE TITLE
[apksigtool] handle "frosting" block in APK Signatures

### ISSUE THREAD

**Issue by eighthave** [obfusk/apksigcopier#46]
The [frosting](https://bi-zone.medium.com/easter-egg-in-apk-files-what-is-frosting-f356aa9f4d1) block in the APK signature can include a separate signature that is tied to the app store that distributed the APK.  _apksigcopier_ should be aware of frosting, and have options to handle it.  I think it should be able to either copy it, or strip it out when copying an APK signature.

Here's some code that works with frosting that @U039b pointed me to:
https://bi-zone.medium.com/easter-egg-in-apk-files-what-is-frosting-f356aa9f4d1

**Comment by obfusk** [comment]
>  I think it should be able to either copy it

It's part of the APK Signature Scheme v2 Block, so it's already being copied.

> or strip it out when copying an APK signature.

I'm considering that; but maybe that's more suited to [`apksigtool`](https://github.com/obfusk/apksigtool).

**Comment by obfusk** [comment]
> Here's some code that works with frosting that @U039b pointed me to:
> https://bi-zone.medium.com/easter-egg-in-apk-files-what-is-frosting-f356aa9f4d1

That's the same link I posted [here](https://salsa.debian.org/reproducible-builds/diffoscope/-/issues/246#note_255463) :)

**Comment by eighthave** [comment]
I like to make sure all the relevant stuff is in the issue so the implementer doesn't have to go on a wild goose chase to find it.  For example, here's a Golang implemenatation which might have been posted elsewehre:
https://github.com/avast/apkverifier/blob/master/signingblock/frosting.go

**Comment by U039b** [comment]
Frosting detection implemented in Python: https://github.com/Pithus/bazaar/blob/master/bazaar/core/tasks.py#L326

**Comment by obfusk** [comment]
I've been working on [`apksigtool`](https://github.com/obfusk/apksigtool), which currently supports parsing the APK Signature Block and validating v2 (and to some extent) v3 signatures.

It detects the frosting block, but doesn't "look inside"; porting the Go code might be interesting if we have a use case for that.

**Comment by eighthave** [comment]
We'll definitely want to be able to strip the frosting block.  Then if its 
possible to have multiple app store signatures there, then being able to add an 
additional one would be useful.  Verifying that signature would also be useful.

**Comment by obfusk** [comment]
We can "invent" our own signature block; I'd be happy to implement that in `apksigtool`.

**Comment by obfusk** [comment]
```sh
$ apksigtool parse original.apk | grep -v '^    '
PAIR ID: 0x7109871a
  APK SIGNATURE SCHEME v2 BLOCK
  SIGNER 0
  VERIFIED
PAIR ID: 0x504b4453
  DEPENDENCY INFO BLOCK
PAIR ID: 0x42726577
  VERITY PADDING BLOCK
PAIR ID: 0x2146444e
  GOOGLE PLAY FROSTING BLOCK
$ cp original.apk cleaned.apk
$ apksigtool clean cleaned.apk
$ apksigtool parse cleaned.apk | grep -v '^    '
PAIR ID: 0x7109871a
  APK SIGNATURE SCHEME v2 BLOCK
  SIGNER 0
  VERIFIED
PAIR ID: 0x504b4453
  DEPENDENCY INFO BLOCK
PAIR ID: 0x42726577
  VERITY PADDING BLOCK
$ apksigtool verify cleaned.apk
WARNING: THIS IS A PROTOTYPE; DO NOT USE IN PRODUCTION!
v2 verified
```

Fun fact: the verity padding block only provides the correct amount of padding after removing the "frosting" block.

**Comment by obfusk** [comment]
Related: https://gitlab.com/fdroid/fdroidserver/-/issues/1056

**Comment by obfusk** [comment]
@U039b @eighthave I haven't worked or stayed up-to-date on this topic for a year, but I'm working on `apksigtool` again.

If you know of any new information or tools from the last year, I'd appreciate a link :)

**Comment by eighthave** [comment]
Great to see you around again!  I don't have any new info on this topic.

**Comment by obfusk** [comment]
> If one was to verify the frosting block to ensure the authenticity of the APK and that it comes from the Play Store, what would the best course of action be?

That's outside of the scope of this project's issue tracker. And AFAIK not documented by Google.
