### ISSUE TITLE
Error: Unexpected metadata

### ISSUE THREAD

**Issue by thinkCreat3** [obfusk/apksigcopier#48]
root@localhost:~# apksigcopier patch meta unsigned.apk out.apk
Error: Unexpected metadata.

**Comment by lepresk** [comment]
Getting same error

**Comment by muhyuddin** [comment]
Any luck with the error? Having the same issue.

**Comment by obfusk** [comment]
Closing this now, please reopen if my answer was not sufficient to address the issue.
