### ISSUE TITLE
Python returning empty `info.extra`

### ISSUE THREAD

**Issue by penn5** [obfusk/apksigcopier#83]
On my machine, https://github.com/obfusk/apksigcopier/blob/master/apksigcopier/__init__.py#L384 is always `b''` on Python 3.11.1, even if there is `extra` data in the zipfile. 
I tried manually inserting `DEADBEEF` after the filename, and `old_xtr` remains `b''`
I don't know what impact this has on the proper functioning of the program.

**Comment by obfusk** [comment]
Already fixed by fcff62fdabb72575cf2113548c7c3b4ef1bb77ea.
