### ISSUE TITLE
ERROR: CHUNKED_SHA256 digest mismatch

### ISSUE THREAD

**Issue by silentshadow88** [obfusk/apksigcopier#87]
successfully copying but when verify this happen

apksigner verify -verbose out.apk                                                             
Picked up _JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=on -Dswing.aatext=true
DOES NOT VERIFY
ERROR: APK Signature Scheme v2 signer #1: APK integrity check failed. CHUNKED_SHA256 digest mismatch. Expected: <2e79069cc57f595e5e37ef0821d516207906b5572df15410d607c22c2dd9b587>, actual: <263c455a0ad9a2c341b037090b148d7b5581e0378b2a91900b10a551a6813047>

**Comment by obfusk** [comment]
Successful copying does not guarantee the copied signature is valid for the APK it was copied to.

I can copy the signature of pretty much any random signed APK to any random unsigned APK *as long as the source APK is larger than the target APK*.

But unless the signed source APK was created from an unsigned APK that's identical to the unsigned target APK, the signature will never be valid for that APK.

It *could* be there's a bug in `apksigcopier` here. But if you want me to investigate that you'll have to show that the verification should have succeeded: i.e. that the signature you copied was valid for the APK you copied it to.

**Comment by silentshadow88** [comment]
i can extract the signature but when verifying the source APK it show this,is it this signature is invalid that caused this problem?

Picked up _JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=on -Dswing.aatext=true
Verifies
Verified using v1 scheme (JAR signing): true
Verified using v2 scheme (APK Signature Scheme v2): true
Verified using v3 scheme (APK Signature Scheme v3): false
Verified using v4 scheme (APK Signature Scheme v4): false
Verified for SourceStamp: false
Number of signers: 1
WARNING: META-INF/com/android/build/gradle/app-metadata.properties not protected by signature. Unauthorized modifications to this JAR entry will not be detected. Delete or move the entry outside of META-INF/.
WARNING: META-INF/androidx.activity_activity-ktx.version not protected by signature. Unauthorized modifications to this JAR entry will not be detected. Delete or move the entry outside of META-INF/.
WARNING: META-INF/androidx.activity_activity.version not protected by signature. Unauthorized modifications to this JAR entry will not be detected. Delete or move the entry outside of META-INF/.
WARNING: META-INF/androidx.annotation_annotation-experimental.version not protected by signature. Unauthorized modifications to this JAR entry will not be detected. Delete or move the entry outside of META-INF/.

**Comment by obfusk** [comment]
> is it this signature is invalid that caused this problem?

No, that's normal. But I have no idea what you're trying to do here.

I know some people have tried to use `apksigcopier` to copy a signature to a modified APK, which will never work.

The only thing that works is copying the signature of a signed APK to an unsigned APK *that was built from the exact same source*.

**Comment by obfusk** [comment]
For the record, as I've [said before](https://github.com/obfusk/apksigcopier/issues/47):

`apksigcopier` requires the unsigned APKs to be identical (otherwise the v2/v3 signature will never be valid) and the signing process -- which may include padding/alignment -- to be identical to that of `apksigner`.

If you **modify any part of the APK** -- whether it's any "string in its resources", ZIP metadata (ordering, timestamps, etc.), alignment/padding, etc. -- **the existing v2/v3 signature will never be valid**, regardless of whether you get an error during copying or not.

**Comment by obfusk** [comment]
> It _could_ be there's a bug in `apksigcopier` here. But if you want me to investigate that you'll have to show that the verification should have succeeded: i.e. that the signature you copied was valid for the APK you copied it to.

I'm happy to reopen and investigate if you can show that this is a bug in `apksigcopier`, but I'm closing this for now.
