### ISSUE TITLE
Error: Unexpected metadata when executing copy command 

### ISSUE THREAD

**Issue by EnzoGamingEzoPlus** [obfusk/apksigcopier#92]
How can i forecome it?

**Comment by obfusk** [comment]
Please note that (as the README says):

> `apksigcopier` is a tool that enables using an [android APK signature](https://source.android.com/docs/security/features/apksigning) as a [build input](https://reproducible-builds.org/docs/embedded-signatures/) (by copying it from a signed APK to an unsigned one), making it possible to create a ([bit-by-bit identical](https://reproducible-builds.org/docs/definition/)) [reproducible build](https://f-droid.org/docs/Reproducible_Builds/) from the source code without having access to the private key used to create the signature.

I don't know what you're trying to do, but e.g. copying a signature to a modified APK is not possible. This is a tool for reproducible builds only. You seem to be trying to copy a signature to an APK that's already signed, hence the error.

If you want me to look into this, please confirm your use case matches the above, and provide more details on what exactly you're trying to do when you get that error.
