### ISSUE TITLE
Error: apksigner command not found.

### ISSUE THREAD

**Issue by ego-lay-atman-bay** [obfusk/apksigcopier#93]
I'm getting an error where it says that apksigner is not installed. Now, I have no idea where it checks, but I do have apksigner, but it's in `C:/android/apksigner.jar` and I have a `C:/android/apksigner.bat` file. I have it set up like this because I didn't really know how to install it correctly. 

How am I supposed to install apksigner to be able to work with apksigcopier?

**Comment by obfusk** [comment]
The `compare` subcommand expects an `apksigner` command (which is part of the Android SDK build tools) on your operating system's PATH (other subcommands do not require `apksigner`).

Providing help installing `apksigner` (and setting PATH properly) is really out of scope for this project's issue tracker, but FWIW you can try using the `--verify-cmd` option to specify the full path to the `.bat` or `.jar`, e.g.:

```
apksigcopier compare --verify-cmd 'C:/android/apksigner.bat verify' x.apk y.apk
```

or

```
apksigcopier compare --verify-cmd 'java -jar C:/android/apksigner.jar verify' x.apk y.apk
```

**Comment by ego-lay-atman-bay** [comment]
thanks, it worked.
